spring:
  redis:
    database: 0
    host: 10.0.0.155
    port: 6379
    timeout: 2000
    lettuce:
      pool:
        max-active: 300
        max-idle: 100
        min-idle: 10
        max-wait: 1000